apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${POSTGRES_NAMESPACE}
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
