apiVersion: v1
kind: Namespace
metadata:
  name: ${POSTGRES_NAMESPACE}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: ${CLUSTER_NAME}
    app.kubernetes.io/part-of: postgres
    app.kubernetes.io/component: database
