apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ${POSTGRES_NAMESPACE}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: ${CLUSTER_NAME}
    app.kubernetes.io/part-of: postgres
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-password: ${POSTGRES_PASSWORD}
  postgres-user: ${POSTGRES_USER}
  postgres-database: ${POSTGRES_DATABASE}
